- name: "Update system"
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: "Install required pacman packages"
  community.general.pacman:
    name:
      - bat
      - blueman
      - eza
      - fcitx5
      - fd
      - fzf
      - git-delta
      - grim
      - kitty
      - lazygit
      - lf
      - neovim
      - polkit-kde-agent
      - ripgrep
      - slurp
      - trash-cli
      - ttf-cascadia-code
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - udiskie
      - wl-clipboard
      - xdg-desktop-portal
      - zsh
    state: present

- name: "Set shell to zsh"
  ansible.builtin.user:
    name: "alice"
    shell: "/bin/zsh"
# TODO: Uncomment this task once ssh keys are set up
# - name: "Clone dotfiles repo to ~/.dotfiles"
#   ansible.builtin.git:
#     repo: "git@github:phinocio/dotfiles.git"
#     dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
#     update: false
#     version: "main"
