- name: "Update system"
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: "Install required pacman packages"
  community.general.pacman:
    name:
      - bat
      - blueman
      - brightnessctl
      - darkman
      - eza
      - fcitx5
      - fcitx5-configtool
      - fd
      - firefox
      - fuzzel
      - fzf
      - git-delta
      - gnome-keyring
      - gnome-themes-extra
      - grim
      - gvfs-smb
      - imagemagick
      - kitty
      - lazygit
      - lf
      - mako
      - man-db
      - man-pages
      - mpv
      - neovim
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - nwg-look
      - obsidian
      - pamixer
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - ripgrep
      - rsync
      - samba
      - seahorse
      - slurp
      - snapper
      - snap-pac
      - starship
      - tmux
      - trash-cli
      - ttf-cascadia-code
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - udiskie
      - unzip
      - waybar
      - wl-clipboard
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      - zsh
    state: present

- name: "Set shell to zsh"
  ansible.builtin.user:
    name: "alice"
    shell: "/bin/zsh"
# - name: "Clone dotfiles repo to ~/.dotfiles"
#   ansible.builtin.git:
#     repo: "git@github:phinocio/dotfiles.git"
#     dest: "{{ lookup('env', 'HOME') }}/dotfiles"
#     update: false
#     version: "main"
